// Generates src/icons/gameIcons.ts with only the icons the game uses, taken from game-icons.net
// (via @iconify-json/game-icons, CC BY 3.0) plus a few icons drawn for this game.
// Usage: npm run icons — after adding a name to GAME_ICONS or CUSTOM_ICONS below.
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const set = JSON.parse(readFileSync(require.resolve('@iconify-json/game-icons/icons.json'), 'utf8'));

const GAME_ICONS = [
  // Resources
  'wood-stick',
  'rock',
  'stone-pile',
  'log',
  'high-grass',
  'vines',
  'rope-coil',
  'flint-spark',
  'sewing-string',
  'rolled-cloth',
  'bandage-roll',
  'feather',
  'square-bottle',
  'broken-arrow',
  'arrow-cluster',
  'broadhead-arrow',
  'three-leaves',
  'ground-sprout',
  'clay-brick',
  'striking-balls',
  // Food
  'coconuts',
  'raspberry',
  'elderberry',
  'mushroom',
  'crab',
  'crab-claw',
  'mussel',
  'oyster',
  'flatfish',
  'fish-cooked',
  'steak',
  'meat',
  'nest-eggs',
  'fried-eggs',
  'cookie',
  'algae',
  'water-bottle',
  'animal-hide',
  'dripping-honey',
  // Equipment
  'shirt',
  't-shirt',
  'billed-cap',
  'hood',
  'belt-armor',
  'leather-vest',
  'leather-armor',
  'outback-hat',
  'poncho',
  'bone-knife',
  'flat-hammer',
  'bow-string',
  'stone-spear',
  'stone-axe',
  'primitive-torch',
  // Buildings
  'campfire',
  'hut',
  'wooden-crate',
  'axe-in-stump',
  'water-tank',
  'sleeping-bag',
  'camping-tent',
  'wood-cabin',
  'fireplace',
  'furnace',
  'table',
  'chest',
  'barn',
  // Animals
  'rabbit',
  'seagull',
  'kiwi-bird',
  'turtle',
  'monkey',
  'snake',
  // Interface
  'person',
  'compass',
  'knapsack',
  'heart-beats',
  'hammer-nails',
  'tied-scroll',
  'fire',
  'hazard-sign',
  'help',
  'thermometer-hot',
  'thermometer-cold',
  'thermometer-scale',
  // Weather
  'sun',
  'fluffy-cloud',
  'wind-slap',
  'raining',
  'lightning-storm',
];

/** Icons drawn for this game in the same 512×512 style. */
const CUSTOM_ICONS = {
  // Half a coconut with its white flesh showing.
  'opened-coconut':
    '<path fill="currentColor" fill-rule="evenodd" d="M56 220A200 56 0 0 1 456 220A200 200 0 0 1 56 220ZM78 222A178 46 0 1 0 434 222A178 46 0 1 0 78 222ZM104 224A152 34 0 1 0 408 224A152 34 0 1 0 104 224Z"/>' +
    '<path fill="currentColor" d="M256 40c-18 34-22 52 0 64 22-12 18-30 0-64zm-84 36c-12 22-14 34 0 42 14-8 12-20 0-42zm168 0c-12 22-14 34 0 42 14-8 12-20 0-42z"/>',
  // An empty half coconut shell.
  'coconut-shell':
    '<path fill="currentColor" fill-rule="evenodd" d="M56 220A200 56 0 0 1 456 220A200 200 0 0 1 56 220ZM84 222A172 42 0 1 0 428 222A172 42 0 1 0 84 222ZM150 318l40 30-10 12-40-30zM250 352l12 48-14 4-12-48zM356 320l-34 38-10-10 34-38z"/>',
};

const bodies = {};
for (const name of GAME_ICONS) {
  const icon = set.icons[name];
  if (!icon) {
    throw new Error(`Icon not found in game-icons: ${name}`);
  }
  bodies[name] = icon.body;
}
Object.assign(bodies, CUSTOM_ICONS);

const names = Object.keys(bodies).sort();
const lines = [
  '// Generated by scripts/build-icons.mjs — do not edit by hand.',
  '// Icons from game-icons.net (Lorc, Delapouite and contributors), licensed CC BY 3.0, plus custom icons.',
  '',
  `export type IconName =\n${names.map((n) => `  | '${n}'`).join('\n')};`,
  '',
  '/** SVG contents of each icon, drawn in a 512×512 view box with currentColor. */',
  'export const ICON_BODIES: Readonly<Record<IconName, string>> = {',
  ...names.map((n) => `  '${n}': ${JSON.stringify(bodies[n])},`),
  '};',
  '',
];
writeFileSync(new URL('../src/icons/gameIcons.ts', import.meta.url), lines.join('\n'));
console.log(`Wrote ${names.length} icons to src/icons/gameIcons.ts`);
